version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'BITCOIN' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'BITCOIN' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: hourly_prices_coin_market_cap
      - name: hourly_prices_coin_gecko
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "BITCOIN_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "BITCOIN" }}
    tables:
      - name: blocks_hash
      - name: blocks
      - name: transactions
